name: linter-check
on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest 
    steps:
    -  name: installation of poetry
       run: pip3 install poetry
    -  name: linter-check
       run: make lint