name: linter-check
on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest 
    steps:
    -  name: installation of poetry
       run: |
            pip3 install poetry
            make lint











    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run test and linter
        run: make check
        env:
          SECRET_KEY: secret
      - name: Publish code coverage report
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          SECRET_KEY: secret
          CC_TEST_REPORTER_ID: ${{secrets.TEST_COVERAGE}}
        with:
          coverageCommand: make test-coverage